### ISSUE TITLE
Error on /cases endpoint

### ISSUE THREAD

**Issue by kdbcinco** [sorxrob/coronavirus-ph-api#16]
Error when accessing the `/cases` endpoint. Tried running on my own instance and here's what I got. 

UPDATE:
Seems like the contents of the Travel History column was moved to styles using `content`. Maybe just map the class name of the `td` i.e, `td.yes === "Yes"`

```
[GET] /cases
15:27:33:39
2020-03-27T07:27:37.786Z	e4a570be-5733-43bf-a3f0-02a36c96ba57	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: Cannot read property 'trim' of undefined","reason":{"errorType":"TypeError","errorMessage":"Cannot read property 'trim' of undefined","stack":["TypeError: Cannot read property 'trim' of undefined","    at travelHistory (/var/task/index.js:46392:18)","    at Node.<anonymous> (/var/task/index.js:46444:45)","    at initialize.module.exports.exports.each (/var/task/index.js:42801:24)","    at Scraper.getCases (/var/task/index.js:46425:8)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)","    at /var/task/index.js:24216:16"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError: Cannot read property 'trim' of undefined","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:323:22)","    at process.emit (/var/task/sourcemap-register.js:1138:21)","    at processPromiseRejections (internal/process/promises.js:209:33)","    at processTicksAndRejections (internal/process/task_queues.js:98:32)"]}
Unknown application error occurred
```

**Comment by kdbcinco** [comment]
@sorxrob Seems like the contents of the Travel History column was moved to styles using `content`. :/

**Comment by sorxrob** [comment]
I'm now checking this. Thanks!

**Comment by sorxrob** [comment]
Fixed. Thank you.

**Comment by kdbcinco** [comment]
Sigh. It was just a bad Wikipedia edit. Found the offending part of the table.

![2020-covid-ph-wikipedia-error](https://user-images.githubusercontent.com/6251471/77734658-11fb7280-7044-11ea-9688-743793f2ff52.PNG)

**Comment by sorxrob** [comment]
> Sigh. It was just a bad Wikipedia edit. Found the offending part of the table.
> 
> ![2020-covid-ph-wikipedia-error](https://user-images.githubusercontent.com/6251471/77734658-11fb7280-7044-11ea-9688-743793f2ff52.PNG)
> 

Yeah. The author got excited.

**Comment by sorxrob** [comment]
Hi, switched to heroku https://coronavirus-ph-api.herokuapp.com/
